name: "Hello World"
description: "Greet someone"
inputs:
  graphql:
    description: "GraphQL query"
    required: true
  jq:
    description: "jq filter"
    required: false
    default: ".data"
outputs:
  graphql:
    description: "The output of the graphql query"
    value: ${{ steps.graphql-query.outputs.graphql-output }}
  jq:
    description: "The output of the graphql query"
    value: ${{ steps.jq-filter.outputs.jq-output }}
runs:
  using: "composite"
  steps:
    - id: graphql-query
      run: |
        printf '{"query": "%s"}' "$INPUT" > graphql-input.json
        curl https://api.github.com/graphql  \
          --silent \
          --header "Authorization: token $GITHUB_TOKEN" \
          --header "Content-Type: application/json" \
          --data '@graphql-input.json' > graphql-output.json
        cat graphql-input.json
        cat graphql-output.json
        echo "::set-output name=graphql-output::$(cat graphql-output.json)"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        QUERY: ${{ inputs.graphql }}
    - id: jq-filter
      run: |
        cat graphql-output.json | jq ${{ inputs.jq }} > jq-output.json
        echo "::set-output name=jq-output::$(cat jq-output.json)"
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
