name: "Hello World"
description: "Greet someone"
inputs:
  graphql:
    description: "GraphQL query"
    required: true
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - uses: octokit/graphql-action@v2.x
        id: graphql-query
        with:
          query: ${{ inputs.graphql }}
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
